### ISSUE TITLE
#12(Navbar): Add hover/focus effect on the hamburger menu icons

### ISSUE THREAD

**Issue by ChelleAmon** [ChelleAmon/Portfolio-2023#22]
Add hover/focus effect on the hamburger menu icons

**Comment by maddy020** [comment]
Hey @ChelleAmon 
I would like to work on this issue
Please give me some details what kind of effect do you want

**Comment by ChelleAmon** [comment]
Hey @maddy020. First of all, thank you for offering your help!

I'm sorry that my description above is vague. I opened this issue just to make my ideas for the navbar more organized. 
 
I only wanted a simple animation effect but I don't have anything in mind yet on how I will execute it. I will come up with something no later than next week and I will let you know.

Feel free to fork my project and play around with it. I am open to collaborations and suggestions so if you come up with an idea before me for this issue, please create a feature branch from the development. Regards!

**Comment by ChelleAmon** [comment]
> Hey @ChelleAmon I would like to work on this issue Please give me some details what kind of effect do you want

Hey @maddy020. First of all, thank you for offering your help!

I'm sorry that my description above is vague. I opened this issue just to make my ideas for the navbar more organized.

I only wanted a simple animation effect but I don't have anything in mind yet on how I will execute it. I will come up with something no later than next week and I will let you know.

Feel free to fork my project and play around with it. I am open to collaborations and suggestions so if you come up with an idea before me for this issue, please create a feature branch from the development. Regards!

**Comment by maddy020** [comment]
Hi @ChelleAmon 
I am so sorry I just read your tech stack in this project and I am not familiar with angular 
I am unable to contribute in this repo

**Comment by ChelleAmon** [comment]
> Hi @ChelleAmon I am so sorry I just read your tech stack in this project and I am not familiar with angular I am unable to contribute in this repo

No worries. Thank you for letting me know :)

**Comment by HyunCafe** [comment]
Could we help with just using css?

**Comment by ChelleAmon** [comment]
> Could we help with just using css?

Definitely! I honestly prefer to use pure CSS or Sass for this issue.

**Comment by HyunCafe** [comment]
I would like to help

**Comment by ChelleAmon** [comment]
> I would like to help 

That is fantastic, thank you! 

My navbar is somewhat messed up, especially on mobile, so I am open to any suggestions you might have. 

Do you have typescript, angular 2 and node.js installed on your computer? You will need them so the project will run. If you need further help setting it up, please let me know.

**Comment by HyunCafe** [comment]
Sounds good, i have node.js installed and i can install the others on my own 
thanks for letting me help!

**Comment by ChelleAmon** [comment]
> Sounds good, i have node.js installed and i can install the others on my own thanks for letting me help!

No problem! Also, thank you! btw, please create a feature branch from development :D

**Comment by HyunCafe** [comment]
Alright, I have it running and am looking at the hamburger menu icon, It seems to be responsive in mobile mode, are you referring to the issue of when you decrease the width too much it, it slowly moves to the left?

**Comment by HyunCafe** [comment]
So I have it up and running, the hover/focus effect seems to be working both as intended already for the desktop and mobile versions, only other thing I notice is that the navbar for mobile moves slightly to the left when the width becomes too narrow for the screen, what should I be looking out for?

Edit* reading above, you would like some simple animation effect added?

**Comment by ChelleAmon** [comment]
> So I have it up and running, the hover/focus effect seems to be working both as intended already for the desktop and mobile versions, only other thing I notice is that the navbar for mobile moves slightly to the left when the width becomes too narrow for the screen, what should I be looking out for?
> 
> Edit* reading above, you would like some simple animation effect added?

For this particular issue, we will focus mainly on adding a hover/focus effect on the hamburger menu icon. And yes, a simple animation effect

About the other bug you just saw, I will create a separate issue for that and I will let you work on it if you want to :) 

Let me know if you have other questions 👍

**Comment by HyunCafe** [comment]
Great, I finished the simple animation I think you will like it!

Also, yes I would be willing to look at the issue (although the screen width being that narrow isn't possible for any mobile device, it would only maybe be looked at if someone was reviewing your portfolio)

**Comment by ChelleAmon** [comment]
> Great, I finished the simple animation I think you will like it!
> 
> Also, yes I would be willing to look at the issue (although the screen width being that narrow isn't possible for any mobile device, it would only maybe be looked at if someone was reviewing your portfolio)

Sounds good, I appreciate it! I intended this issue to be small, but if you find any bugs, especially on the navbar and you want to work on those, you can create a pull request right away 😃

**Comment by ChelleAmon** [comment]
@HyunCafe I just created a new issue #38

**Comment by ChelleAmon** [comment]
Closing issue.
