### ISSUE TITLE
#21(Navbar): Fix alignment/layout

### ISSUE THREAD

**Issue by ChelleAmon** [ChelleAmon/Portfolio-2023#38]
Bug Description: Navbar for mobile moves slightly to the left when the width becomes too narrow for the screen

**Comment by HyunCafe** [comment]
i can help

**Comment by ChelleAmon** [comment]
> i can help

Hey! I am not sure if the project is still running on your local computer. If you do, can you please take a screenshot of that bug?

**Comment by HyunCafe** [comment]
hey! sorry i forgot about this, i don't have the local repo running again, but it only happened when it was super narrow ( i don't think it is a real issue) just view i on mobile mode and try to decrease the width till you can replicate it, 
no device is that narrow tho haha

**Comment by ChelleAmon** [comment]
> hey! sorry i forgot about this, i don't have the local repo running again, but it only happened when it was super narrow ( i don't think it is a real issue) just view i on mobile mode and try to decrease the width till you can replicate it, no device is that narrow tho haha

Ah I see... I will close this issue then and I will reopen it in the future if necessary. Thanks again.
